# Generated by Django 5.2.5 on 2025-08-27 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название направления')),
                ('years_of_study', models.PositiveSmallIntegerField(verbose_name='Количество лет обучения')),
                ('description', models.TextField(blank=True, verbose_name='Описание направления')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('phone_parent', models.CharField(max_length=20, verbose_name='Телефон родителя')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_study', models.PositiveSmallIntegerField(verbose_name='Год обучения')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('schedule', models.CharField(max_length=200, verbose_name='Расписание')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='music_school.direction', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['direction', 'year_of_study', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='Дата зачисления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активное обучение')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_school.group', verbose_name='Группа')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_school.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Зачисление',
                'verbose_name_plural': 'Зачисления',
                'unique_together': {('student', 'group')},
            },
        ),
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(through='music_school.Enrollment', through_fields=('group', 'student'), to='music_school.student', verbose_name='Студенты'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('is_active', models.BooleanField(default=True, verbose_name='Преподаёт')),
                ('directions', models.ManyToManyField(related_name='teachers', to='music_school.direction', verbose_name='Направления')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='music_school.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('direction', 'year_of_study', 'name')},
        ),
    ]
